--- #YAML:1.0
name:                Hardware-PortScanner
version:             0.51
abstract:            Scan serial ports to find hardware devices at various com ports, baud rates, and settings using request and expected reply message
license:             perl
author:              
    - John Dennis <jdennis30064@galileotech.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Device::SerialPort:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
